# Generated by Django 4.1.5 on 2023-01-31 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='stories/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='%(class)s_created_by', to='user.user')),
                ('views', models.ManyToManyField(related_name='%(class)s_viewed_by', to='user.user')),
            ],
        ),
    ]
