# Generated by Django 4.1.5 on 2023-01-31 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=True)),
                ('send', models.ManyToManyField(related_name='%(class)s_send_to', to='user.user')),
                ('user', models.ManyToManyField(related_name='%(class)s_created_by', to='user.user')),
            ],
        ),
    ]
