# Generated by Django 4.1.5 on 2023-01-31 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Post', 'POST'), ('Story', 'STORY'), ('Reels', 'REELS')], max_length=50)),
                ('type_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('share', models.ManyToManyField(related_name='shares', to='user.user')),
                ('user', models.ManyToManyField(related_name='users', to='user.user')),
            ],
        ),
    ]
